/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RateLimitedRouteImport } from './routes/rate-limited'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAuthorizationsRouteImport } from './routes/account/authorizations'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthFailedRouteImport } from './routes/auth/failed'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as DeveloperIndexRouteImport } from './routes/developer/index'
import { Route as DeveloperOauthTestRouteImport } from './routes/developer/oauth-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RateLimitedRoute = RateLimitedRouteImport.update({
  id: '/rate-limited',
  path: '/rate-limited',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAuthorizationsRoute = AccountAuthorizationsRouteImport.update({
  id: '/account/authorizations',
  path: '/account/authorizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFailedRoute = AuthFailedRouteImport.update({
  id: '/auth/failed',
  path: '/auth/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperOauthTestRoute = DeveloperOauthTestRouteImport.update({
  id: '/developer/oauth-test',
  path: '/developer/oauth-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/architecture': typeof ArchitectureRoute
  '/authorize': typeof AuthorizeRoute
  '/callback': typeof CallbackRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/maintenance': typeof MaintenanceRoute
  '/mcp': typeof McpRoute
  '/not-found': typeof NotFoundRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/rate-limited': typeof RateLimitedRoute
  '/redirect': typeof RedirectRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/session-expired': typeof SessionExpiredRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/authorizations': typeof AccountAuthorizationsRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/failed': typeof AuthFailedRoute
  '/auth/success': typeof AuthSuccessRoute
  '/developer/oauth-test': typeof DeveloperOauthTestRoute
  '/account/': typeof AccountIndexRoute
  '/developer/': typeof DeveloperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/architecture': typeof ArchitectureRoute
  '/authorize': typeof AuthorizeRoute
  '/callback': typeof CallbackRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/maintenance': typeof MaintenanceRoute
  '/mcp': typeof McpRoute
  '/not-found': typeof NotFoundRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/rate-limited': typeof RateLimitedRoute
  '/redirect': typeof RedirectRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/session-expired': typeof SessionExpiredRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/authorizations': typeof AccountAuthorizationsRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/failed': typeof AuthFailedRoute
  '/auth/success': typeof AuthSuccessRoute
  '/developer/oauth-test': typeof DeveloperOauthTestRoute
  '/account': typeof AccountIndexRoute
  '/developer': typeof DeveloperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/architecture': typeof ArchitectureRoute
  '/authorize': typeof AuthorizeRoute
  '/callback': typeof CallbackRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/maintenance': typeof MaintenanceRoute
  '/mcp': typeof McpRoute
  '/not-found': typeof NotFoundRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/rate-limited': typeof RateLimitedRoute
  '/redirect': typeof RedirectRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/session-expired': typeof SessionExpiredRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/authorizations': typeof AccountAuthorizationsRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/failed': typeof AuthFailedRoute
  '/auth/success': typeof AuthSuccessRoute
  '/developer/oauth-test': typeof DeveloperOauthTestRoute
  '/account/': typeof AccountIndexRoute
  '/developer/': typeof DeveloperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/architecture'
    | '/authorize'
    | '/callback'
    | '/error'
    | '/forgot-password'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/maintenance'
    | '/mcp'
    | '/not-found'
    | '/privacy'
    | '/projects'
    | '/rate-limited'
    | '/redirect'
    | '/register'
    | '/reset-password'
    | '/roadmap'
    | '/services'
    | '/session-expired'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/account/authorizations'
    | '/account/security'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/failed'
    | '/auth/success'
    | '/developer/oauth-test'
    | '/account/'
    | '/developer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/architecture'
    | '/authorize'
    | '/callback'
    | '/error'
    | '/forgot-password'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/maintenance'
    | '/mcp'
    | '/not-found'
    | '/privacy'
    | '/projects'
    | '/rate-limited'
    | '/redirect'
    | '/register'
    | '/reset-password'
    | '/roadmap'
    | '/services'
    | '/session-expired'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/account/authorizations'
    | '/account/security'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/failed'
    | '/auth/success'
    | '/developer/oauth-test'
    | '/account'
    | '/developer'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/architecture'
    | '/authorize'
    | '/callback'
    | '/error'
    | '/forgot-password'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/maintenance'
    | '/mcp'
    | '/not-found'
    | '/privacy'
    | '/projects'
    | '/rate-limited'
    | '/redirect'
    | '/register'
    | '/reset-password'
    | '/roadmap'
    | '/services'
    | '/session-expired'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/account/authorizations'
    | '/account/security'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/failed'
    | '/auth/success'
    | '/developer/oauth-test'
    | '/account/'
    | '/developer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AuthorizeRoute: typeof AuthorizeRoute
  CallbackRoute: typeof CallbackRoute
  ErrorRoute: typeof ErrorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MaintenanceRoute: typeof MaintenanceRoute
  McpRoute: typeof McpRoute
  NotFoundRoute: typeof NotFoundRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  RateLimitedRoute: typeof RateLimitedRoute
  RedirectRoute: typeof RedirectRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  ServicesRoute: typeof ServicesRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AccountAuthorizationsRoute: typeof AccountAuthorizationsRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthFailedRoute: typeof AuthFailedRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  DeveloperOauthTestRoute: typeof DeveloperOauthTestRoute
  AccountIndexRoute: typeof AccountIndexRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-limited': {
      id: '/rate-limited'
      path: '/rate-limited'
      fullPath: '/rate-limited'
      preLoaderRoute: typeof RateLimitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/authorizations': {
      id: '/account/authorizations'
      path: '/account/authorizations'
      fullPath: '/account/authorizations'
      preLoaderRoute: typeof AccountAuthorizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/failed': {
      id: '/auth/failed'
      path: '/auth/failed'
      fullPath: '/auth/failed'
      preLoaderRoute: typeof AuthFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/oauth-test': {
      id: '/developer/oauth-test'
      path: '/developer/oauth-test'
      fullPath: '/developer/oauth-test'
      preLoaderRoute: typeof DeveloperOauthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  ArchitectureRoute: ArchitectureRoute,
  AuthorizeRoute: AuthorizeRoute,
  CallbackRoute: CallbackRoute,
  ErrorRoute: ErrorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MaintenanceRoute: MaintenanceRoute,
  McpRoute: McpRoute,
  NotFoundRoute: NotFoundRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  RateLimitedRoute: RateLimitedRoute,
  RedirectRoute: RedirectRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  ServicesRoute: ServicesRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AccountAuthorizationsRoute: AccountAuthorizationsRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthFailedRoute: AuthFailedRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  DeveloperOauthTestRoute: DeveloperOauthTestRoute,
  AccountIndexRoute: AccountIndexRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
